### ISSUE TITLE
cannot find font ''

### ISSUE THREAD

**Issue by eserte** [ctrlo/CtrlO-PDF#2] opened 2018-10-25 10:59 UTC
On some of my smoker systems (freebsd, centos6) the test suite fails:
```
cannot find font '' ... at /home/cpansand/.cpan/build/2018102519/PDF-API2-2.033-M9O_lL/blib/lib/PDF/API2/Resource/CIDFont/TrueType/FontFile.pm line 426.
# Looks like your test exited with 2 before it could output anything.
t/002_basic.t .. 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 1/1 subtests 
```

**Comment by tomhukins** [comment] 2019-04-15 09:29
I've written a horrid, but working, patch for this in #3.

**Comment by abeverley** [comment] 2019-04-15 11:50
Thanks - merged and new version released. A better longer term solution might be to allow the module to not rely on any fonts, but this will suffice for the time being.

**Closed as completed by abeverley** 2019-04-15 11:50 UTC

**Comment by eserte** [comment] 2019-04-16 05:14
Unfortunately 0.02 still fails (@tomhukins: FYI). Actually I don't see any real diff between 0.01 and 0.02: https://metacpan.org/diff/file?target=ABEVERLEY/CtrlO-PDF-0.02/&source=ABEVERLEY%2FCtrlO-PDF-0.01

**Comment by tomhukins** [comment] 2019-04-16 07:52
On Mon, Apr 15, 2019 at 10:14:49PM -0700, Slaven Rezić wrote:
> Unfortunately 0.02 still fails (@tomhukins: FYI). Actually I don't see
> any real diff between 0.01 and 0.02:
> https://metacpan.org/diff/file?target=ABEVERLEY/CtrlO-PDF-0.02/&source=ABEVERLEY%2FCtrlO-PDF-0.01

Thanks for the update, Slaven.  Andy, it looks like the two font files I
added in e2e4b27d14c7e1bbf776feb4 weren't included in the release
tarball, so the problem is only fixed in the git repository.

Tom
